name: nge_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5
  go_router: ^15.2.3
  infinite_scroll_pagination: ^5.1.0
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_remote_config: ^5.4.5
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/img/

flutter_gen:
  output: lib/assets/