// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSk4Sm6nbRr56zQPuW_O-YMkUi8x-AMnw',
    appId: '1:1082843459756:android:197246330b552597f1ef09',
    messagingSenderId: '1082843459756',
    projectId: 'my-personal-project-da872',
    storageBucket: 'my-personal-project-da872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX5cffSzD1kh4o0eqORs_25y0skScsGyU',
    appId: '1:1082843459756:ios:1ed1e65d58e1db6bf1ef09',
    messagingSenderId: '1082843459756',
    projectId: 'my-personal-project-da872',
    storageBucket: 'my-personal-project-da872.firebasestorage.app',
    androidClientId: '1082843459756-0qv1kv0pun8r98cssftdbqe5vfci26ov.apps.googleusercontent.com',
    iosClientId: '1082843459756-iqc9fd8i68ntn5i9491ba9767mucvuc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngeStore',
  );

}